//
//  CocktailDetailPresenter.swift
//  Cocktails
//
//  Created by Oleg Stepanov on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CocktailDetailPresentationLogic {
    func presentSomething(response: CocktailDetail.Something.Response)
}

class CocktailDetailPresenter: CocktailDetailPresentationLogic {
    weak var viewController: CocktailDetailDisplayLogic?

    // MARK: Parse and calc respnse from CocktailDetailInteractor and send simple view model to CocktailDetailViewController to be displayed

    func presentSomething(response: CocktailDetail.Something.Response) {
        let viewModel = CocktailDetail.Something.ViewModel(drink: response.drink)
        viewController?.displayCocktailData(viewModel: viewModel)
    }
}
